### ISSUE TITLE
Broken link between files

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebApplications_Final#14]
Somehow in implimenting my template I broke the link to my algorithms file, I'm getting the error that `Algorithms is not defined` in interface.js, which is my algorithms class that I made. I'm not sure what I even changed.

**Comment by skiadas** [comment]
Where in your interface.js file are you telling it where to find the algorithms file?

**Comment by TrikkStar** [comment]
It should be in line 2 when I'm defining algorithms as one of the requirements. Unless I'm mistaken, it worked before I added the template anyway.

**Comment by skiadas** [comment]
All I see in line 2 is that the function within define expects some modules as arguments. Unless you give it a string array before that, showing where to find those modules, it won't work. Look at the AMD examples.

**Comment by TrikkStar** [comment]
Ok. That's a simple enough fix. Not sure why it was working before though.
