### ISSUE TITLE
Parse Error while reading template

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebApplications_Final#15]
@skiadas, getting the following error in the console
`Error: Parse error on line 26:
... Output</h3></div>
---------------------^
Expecting 'OPEN_INVERSE_CHAIN', 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF'`

**Comment by skiadas** [comment]
Look at how `{{#each ...}}` is meant to be implemented.

**Comment by TrikkStar** [comment]
Isn't it supposed to iterate over all the given elements in a given array?

**Comment by skiadas** [comment]
What code is it going to iterate and repeat for each element in the array? from where to where? Look at examples of `#each` from the handlebars page and how they compare to yours. You are missing a crucial element.

**Comment by TrikkStar** [comment]
Ah, I seem to have forgot to terminate the loop.

**Comment by skiadas** [comment]
Exactly, and that was causing a parse error as the program reached end of file without "closing" the loop.
