### ISSUE TITLE
Unsure how to dynamically add multiple copies of a div

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebApplications_Final#18]
I'm trying to make multiple selector boxes, a number equal to the value of `quantity`, but am unsure how to procede. Also the selector which should be populated by my algorithms is empty.

**Comment by skiadas** [comment]
If you want to have multiple algorithms on at the same time, in those different selector boxes, I'm suspecting you'll need to keep in your model the information on which algorithms correspond to which "boxes". So the way I see it part of your model should be an array/list of the algorithms that have been selected.

So I would start with that: This is information your model needs to maintain.

**Comment by TrikkStar** [comment]
That sounds like a good idea, though I'm a step behind that in that I'm not sure how to impliment selection of multiple algorithms, the number of which is based on the number selected to compare in the previous selector.

**Comment by skiadas** [comment]
The number of algorithms to select is also part of your model. In fact if you store the selected algorithms in an array, it will be the length of that array. So when someone chooses say "2", you would need to update your model with that information, and make sure it has somewhere some array with two algorithms selected (you may have to default to a selection here, like the first algorithm in the list of available algorithms).

**Comment by TrikkStar** [comment]
The problem I'm currently runnin into is that the handlebars {{#each }} tag doesn't seem to be populating my selector, despite it being given the correct algorithm.

**Comment by skiadas** [comment]
There's probably something not quite right with the "option" tags there, make sure you've quoted everywhere where you should have quotes, and that you closed the tags properly etc. It often helps to have it print out the HTML as a string, then look at it.

**Comment by TrikkStar** [comment]
How do I view the HTML as a string?

**Comment by skiadas** [comment]
You can `console.log` the return value of the template function call. Or you can also view the HTML code produced in the page, in the developer tools, that might give you some indications.

**Comment by TrikkStar** [comment]
Believe that this issue is no longer relavent due to changer I've made in the implimentation.
