### ISSUE TITLE
Array.prototype.slice() is not working correctly

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebApplications_Final#20]
@skiadas, I am not sure what I did but somehow the array method .slice() is not working correctly in my mergesot function. It somehow sets elements 2, 3, 4, 7, 8, and 9 to undefined, rather than copying them to the defined assingment.

**Comment by skiadas** [comment]
You'll have to give me some more context, which line we're talking about, the test you are running etc. The only calls to "slice" that I found should be just making a copy of the array. So there must be something else going on.

**Comment by skiadas** [comment]
This line (74) is suspicious:

```
arrayCopy(arrA, n / 2, arrC, 0, Math.floor(n / 2 + 1));
```

n/2 will not be an integer.

**Comment by TrikkStar** [comment]
It seems like there are. I was specifically refering to line 180 in algorithms. Running it gave be a disrupted copy when I printed it out on line 181, but when I commented out line 182 it worked as expected.

**Comment by TrikkStar** [comment]
Ah, more leftover intiger division. Thought I cleaned that all up.

**Comment by TrikkStar** [comment]
That fixed it up
