### ISSUE TITLE
odd syntax error

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/WebApplications_Final#5]
@skiadas, In my implimentation of interface.js I'm getting a syntax error on the console when I load index.html `missing ) after formal parameters` on line 2 of interface.js. Running  eslint on the file it throws an error in regards to the `-` in `function(algorithms, handlebars-v3)`. Removing this causes handlebars to timeout while loading, but including it allows the page to load sucessfully but gives me the odd syntax error. Any thoughts on what the problem here is?

**Comment by skiadas** [comment]
You can't use "-" as part of a variable's name. So you should name the variable just "handlebars". Then you got to figure out why it's timing out. But as it stands it's not even given a chance to time out.

**Comment by TrikkStar** [comment]
I thought that was probably the cause. Any suggestions on how I would go about determining why it times out?

**Comment by skiadas** [comment]
Handlebars is one of those packages that don't play too well with AMD loaders. You will want to add a "path" to it in the main.js config, alongside what we did for jquery. Then just refer to it as "handlebars" without any other path information.

**Comment by TrikkStar** [comment]
That fixed it, thank you very much.
